// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookupApi.Models;

namespace ParksLookupApi.Migrations
{
    [DbContext(typeof(ParksLookupApiContext))]
    [Migration("20200131215606_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksLookupApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.Property<string>("State");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            City = "Mariposa",
                            Name = "Yosemite",
                            Rating = 5,
                            Review = "It's Yosemite, dude. So yeah, it's pretty awesome.",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 2,
                            City = "Columbia Falls",
                            Name = "Glacier",
                            Rating = 5,
                            Review = "Feels like a John Wayne movie.",
                            State = "Montana"
                        },
                        new
                        {
                            ParkId = 3,
                            City = "Moab",
                            Name = "Arches",
                            Rating = 4,
                            Review = "How did the Mormons get such a pretty state.",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 4,
                            City = "Ozark",
                            Name = "Jackson Falls",
                            Rating = 2,
                            Review = "It's not too grand, but it's better than the cornfields.",
                            State = "Illinois"
                        },
                        new
                        {
                            ParkId = 5,
                            City = "Estes Park",
                            Name = "Rocky Mountain",
                            Rating = 5,
                            Review = "So beautiful I had trouble breathing, or maybe that was just the elevation.",
                            State = "Colorado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
